console.log("Hello JavaScript");
console.log("learn more about git");
console.log("learn more about git");
console.log("learn more about git");
console.log("learn more about git");
console.log("learn more about git");
console.log("learn more about git");
console.log("learn more about git");
console.log("learn more about git");
console.log("learn more about git");
console.log("learn more about git");
console.log("learn more about git");
